config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :tiendas

  resources :categoria

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  has_many :tiendas
end

app/models/categorium.rb
class Categorium < ActiveRecord::Base
end

app/models/tienda.rb
class Tienda < ActiveRecord::Base
  belongs_to :user
  belongs_to :categoria
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  attr_accessor :login
  
  #->Prelang (user_login:devise/username_login_support)
  has_many :tiendas
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.downcase}]).first
    else
      where(conditions).first
    end
  end


  devise authentication_keys: [:login]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  #->Prelang (user_login:devise)
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up)        { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in)        { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end


  private
  
  #-> Prelang (user_login:devise)
  def require_user_signed_in
    unless user_signed_in?

      # If the user came from a page, we can send them back.  Otherwise, send
      # them to the root path.
      if request.env['HTTP_REFERER']
        fallback_redirect = :back
      elsif defined?(root_path)
        fallback_redirect = root_path
      else
        fallback_redirect = "/"
      end

      redirect_to fallback_redirect, flash: {error: "You must be signed in to view this page."}
    end
  end

end

app/controllers/categoria_controller.rb
class CategoriaController < ApplicationController
  before_action :set_categorium, only: [:show, :edit, :update, :destroy]

  # GET /categoria
  # GET /categoria.json
  def index
    @categoria = Categorium.all
  end

  # GET /categoria/1
  # GET /categoria/1.json
  def show
  end

  # GET /categoria/new
  def new
    @categorium = Categorium.new
  end

  # GET /categoria/1/edit
  def edit
  end

  # POST /categoria
  # POST /categoria.json
  def create
    @categorium = Categorium.new(categorium_params)

    respond_to do |format|
      if @categorium.save
        format.html { redirect_to @categorium, notice: 'Categorium was successfully created.' }
        format.json { render :show, status: :created, location: @categorium }
      else
        format.html { render :new }
        format.json { render json: @categorium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categoria/1
  # PATCH/PUT /categoria/1.json
  def update
    respond_to do |format|
      if @categorium.update(categorium_params)
        format.html { redirect_to @categorium, notice: 'Categorium was successfully updated.' }
        format.json { render :show, status: :ok, location: @categorium }
      else
        format.html { render :edit }
        format.json { render json: @categorium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categoria/1
  # DELETE /categoria/1.json
  def destroy
    @categorium.destroy
    respond_to do |format|
      format.html { redirect_to categoria_url, notice: 'Categorium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categorium
      @categorium = Categorium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def categorium_params
      params.require(:categorium).permit(:nombre)
    end
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def index
  end
end

app/controllers/tiendas_controller.rb
class TiendasController < ApplicationController
  before_action :set_tienda, only: [:show, :edit, :update, :destroy]

  # GET /tiendas
  # GET /tiendas.json
  def index
    @tiendas = Tienda.all
  end

  # GET /tiendas/1
  # GET /tiendas/1.json
  def show
  end

  # GET /tiendas/new
  def new
    @tienda = Tienda.new
  end

  # GET /tiendas/1/edit
  def edit
  end

  # POST /tiendas
  # POST /tiendas.json
  def create
    @tienda = Tienda.new(tienda_params)

    respond_to do |format|
      if @tienda.save
        format.html { redirect_to @tienda, notice: 'Tienda was successfully created.' }
        format.json { render :show, status: :created, location: @tienda }
      else
        format.html { render :new }
        format.json { render json: @tienda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tiendas/1
  # PATCH/PUT /tiendas/1.json
  def update
    respond_to do |format|
      if @tienda.update(tienda_params)
        format.html { redirect_to @tienda, notice: 'Tienda was successfully updated.' }
        format.json { render :show, status: :ok, location: @tienda }
      else
        format.html { render :edit }
        format.json { render json: @tienda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tiendas/1
  # DELETE /tiendas/1.json
  def destroy
    @tienda.destroy
    respond_to do |format|
      format.html { redirect_to tiendas_url, notice: 'Tienda was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tienda
      @tienda = Tienda.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tienda_params
      params.require(:tienda).permit(:nombre, :ciudad, :user_id, :direccion, :local, :telefono, :descripcion, :categoria_id)
    end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  include ApplicationHelper

  def new
    super
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end

  def edit
    super
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/tiendas_helper.rb
module TiendasHelper
end

app/views/categoria/_form.html.erb
<%= form_for @categoria, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :nombre, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :nombre, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  categoria_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/categoria/edit.html.erb
<%- model_class = Categoria -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Categoria %></h1>
</div>
<%= render :partial => 'form' %>

app/views/categoria/index.html.erb
<%- model_class = Categoria -%>
<div class="page-header">
  <h1><%=t '.title', :default => Categoria %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @categoria.each do |categoria| %>
      <tr>
        <td><%= categoria.id %></td>
        <td><%= categoria.nombre %></td>
        <td><%=l categoria.created_at, format: :long %></td>
        <td>
          <%= link_to categoria_path(categoria), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to categoria_path(categoria), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_categoria_path,
            :class => 'btn btn-primary' %>

app/views/categoria/new.html.erb
<%- model_class = Categoria -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Categoria %></h1>
</div>
<%= render :partial => 'form' %>

app/views/categoria/show.html.erb
<%- model_class = Categoria -%>
<div class="page-header">
  <h1><%=t '.title', :default => Categoria %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:nombre) %></dt>
      <dd><pre class="prettyprint"><%= @categoria.nombre %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              categoria_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_categoria_path(@categoria), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              categoria_path(@categoria),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "My Application", defined?(root_path) ? root_path : "#", class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if defined?(Devise) %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/landings/index.html.erb
<h1>Landings#index</h1>
<p>Find me in app/views/landings/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Micentro</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1"/></head>
<body>
<%= render partial: "elements/navbar" %>
<%= bootstrap_flash %>


<%= yield %>

</body>
</html>

app/views/tiendas/_form.html.erb
<%= form_for @tienda, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :nombre, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :nombre, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :ciudad, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :ciudad, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :direccion, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :direccion, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :local, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :local, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :telefono, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :telefono, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :descripcion, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :descripcion, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  tiendas_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/tiendas/edit.html.erb
<%- model_class = Tienda -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Tienda %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tiendas/index.html.erb
<%- model_class = Tienda -%>
<div class="page-header">
  <h1><%=t '.title', :default => Tienda %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th><%= model_class.human_attribute_name(:ciudad) %></th>
      <th><%= model_class.human_attribute_name(:direccion) %></th>
      <th><%= model_class.human_attribute_name(:local) %></th>
      <th><%= model_class.human_attribute_name(:telefono) %></th>
      <th><%= model_class.human_attribute_name(:descripcion) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tiendas.each do |tienda| %>
      <tr>
        <td><%= tienda.id %></td>
        <td><%= tienda.nombre %></td>
        <td><%= tienda.ciudad %></td>
        <td><%= tienda.direccion %></td>
        <td><%= tienda.local %></td>
        <td><%= tienda.telefono %></td>
        <td><%= tienda.descripcion %></td>
        <td><%=l tienda.created_at, format: :long %></td>
        <td>
          <%= link_to tienda_path(tienda), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to tienda_path(tienda), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_tienda_path,
            :class => 'btn btn-primary' %>

app/views/tiendas/new.html.erb
<%- model_class = Tienda -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Tienda %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tiendas/show.html.erb
<%- model_class = Tienda -%>
<div class="page-header">
  <h1><%=t '.title', :default => Tienda %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:nombre) %></dt>
      <dd><pre class="prettyprint"><%= @tienda.nombre %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:ciudad) %></dt>
      <dd><pre class="prettyprint"><%= @tienda.ciudad %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:direccion) %></dt>
      <dd><pre class="prettyprint"><%= @tienda.direccion %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:local) %></dt>
      <dd><pre class="prettyprint"><%= @tienda.local %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:telefono) %></dt>
      <dd><pre class="prettyprint"><%= @tienda.telefono %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:descripcion) %></dt>
      <dd><pre class="prettyprint"><%= @tienda.descripcion %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              tiendas_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_tienda_path(@tienda), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              tienda_path(@tienda),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>